import json
import logging
from pydantic import BaseModel, Field
from gemini_client import get_vertex_client, FAST_MODEL, make_config
import os
import time

client = get_vertex_client()
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

logger = logging.getLogger(__name__)

class PDFContentOutput(BaseModel):
    document_1_summary: str = Field(description="Content for Case Summary Report. Must be English or Roman Urdu.")
    document_2_draft: str = Field(description="Content for Legal Draft. Must be English or Roman Urdu.")
    document_3_aid: str = Field(description="Content for Free Legal Aid Request. Must be English or Roman Urdu.")

system_prompt = """
You are INSAAF OS PDFFormatter.

Compile all agent outputs, retrieved laws, procedures, and draft notice templates into 3 professional, fully articulated legal documents.
Accept FULL or PARTIAL outputs — never crash.
If any agent output missing: use placeholder.

Document 1 — Case Summary Report:
- User problem (2-3 sentences)
- Case category + confidence
- Rights summary (bullet points)
- Readiness Score with breakdown
- Missing documents with costs
- Key risks highlighted
- INJECT ALL RETRIEVED STATUTORY LAWS AND COURT PROCEDURES IN DETAIL WITH CITATIONS (e.g. Specific Relief Act 1877 Section 8).

Document 2 — Legal Draft:
Compile and format the provided legal draft template based on case type:
- Property dispute / general civil dispute → Format and include the generated LEGAL NOTICE TO OPPONENT.
- Criminal offenses / police issues → Format and include the generated FIRST INFORMATION REPORT (FIR) APPLICATION DRAFT.
- Other issues → Format and include the generated SOLEMN AFFIDAVIT.
Ensure all details are fully fleshed out with placeholders [User Name], [Opponent Name], etc., where details are missing.

Document 3 — Free Legal Aid Request Letter:
- Professional format
- Formal request to the closest legal aid body (DLEC, Punjab/Sindh Bar Council, or AGHS Legal Aid Cell) using details from retrieved resources.
- Case summary included
- Placeholders for user personal details

Every document MUST end with:
DISCLAIMER: Generated by INSAAF OS for informational purposes only. Not legal advice. Consult a licensed lawyer before taking action.

CRITICAL RULE: The language for the PDF content MUST BE ENGLISH OR ROMAN URDU ONLY. DO NOT USE URDU SCRIPT.
Return ONLY valid JSON. Do not include markdown formatting.
"""

def _call_gemini(combined_context: dict, templates_context: str):
    prompt = f"Draft Templates Context:\n{templates_context}\n\nContext:\n{json.dumps(combined_context)}"
    response = client.models.generate_content(
        model=FAST_MODEL,
        contents=prompt,
        config=make_config(
            system_instruction=system_prompt,
            response_mime_type="application/json",
            response_schema=PDFContentOutput,
        ),
    )
    return response.text

def _create_pdf(filename: str, title: str, content: str):
    os.makedirs("outputs", exist_ok=True)
    filepath = os.path.join("outputs", filename)
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    story.append(Paragraph(title, styles['Title']))
    story.append(Spacer(1, 12))
    
    # Split content by newlines and add to story
    for line in content.split('\n'):
        if line.strip():
            story.append(Paragraph(line.strip(), styles['Normal']))
            story.append(Spacer(1, 6))
            
    doc.build(story)
    return filepath

def run_pdf_formatter(combined_context: dict, on_trace=None) -> dict:
    try:
        from tools.legal_tools import generate_notice, generate_affidavit, generate_fir_draft
        
        # Generate legal drafts using unified legal tools
        notice_draft = generate_notice(combined_context, on_trace=on_trace)
        affidavit_draft = generate_affidavit(combined_context, on_trace=on_trace)
        fir_draft = generate_fir_draft(combined_context, on_trace=on_trace)
        
        templates_context = (
            f"=== GENERATED LEGAL NOTICE DEMAND ===\n{notice_draft}\n\n"
            f"=== GENERATED SOLEMN AFFIDAVIT ===\n{affidavit_draft}\n\n"
            f"=== GENERATED FIR APPLICATION DRAFT ===\n{fir_draft}\n"
        )
        
        # Save generated drafts under tool_outputs
        combined_context.setdefault("tool_outputs", {})
        combined_context["tool_outputs"]["PDFFormatter"] = {
            "notice_draft": notice_draft,
            "affidavit_draft": affidavit_draft,
            "fir_draft": fir_draft
        }
        
        result_str = _call_gemini(combined_context, templates_context)
        res = json.loads(result_str)
        
        timestamp = int(time.time())
        doc1_path = _create_pdf(f"INSAAF_CaseSummary_{timestamp}.pdf", "Case Summary Report", res.get("document_1_summary", "Missing Content"))
        doc2_path = _create_pdf(f"INSAAF_LegalDraft_{timestamp}.pdf", "Legal Draft", res.get("document_2_draft", "Missing Content"))
        doc3_path = _create_pdf(f"INSAAF_LegalAidLetter_{timestamp}.pdf", "Free Legal Aid Request Letter", res.get("document_3_aid", "Missing Content"))
        
        return {
            "status": "success",
            "pdf_files": [doc1_path, doc2_path, doc3_path]
        }
    except Exception as e:
        logger.error(f"Agent 8 failed: {e}")
        return {
            "agent": "PDFFormatter",
            "status": "failed",
            "fallback_used": True,
            "partial_output": {},
            "reason": str(e),
            "instruction_to_next_agent": "pipeline finished",
            "pdf_files": []
        }
