import json
import logging
from pydantic import BaseModel, Field
from gemini_client import run_agent_with_retry
from google import genai
import os
import time
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

logger = logging.getLogger(__name__)

class PDFContentOutput(BaseModel):
    document_1_summary: str = Field(description="Content for Case Summary Report. Must be English or Roman Urdu.")
    document_2_draft: str = Field(description="Content for Legal Draft. Must be English or Roman Urdu.")
    document_3_aid: str = Field(description="Content for Free Legal Aid Request. Must be English or Roman Urdu.")

system_prompt = """
You are INSAAF OS PDFFormatter.

Compile all agent outputs into 3 documents.
Accept FULL or PARTIAL outputs — never crash.
If any agent output missing: use placeholder.

Document 1 — Case Summary Report:
- User problem (2-3 sentences)
- Case category + confidence
- Rights summary (bullet points)
- Readiness Score with breakdown
- Missing documents with costs
- Key risks highlighted

Document 2 — Legal Draft:
Based on case type generate:
- inheritance → Succession Certificate Application
- property_dispute → Legal Notice to opponent
- criminal_fir → FIR Application Draft
- family_law → Khula/Maintenance Application
- labour_rights → Labour Complaint Letter
- tenancy → Eviction/Rent dispute notice
- government_services → Formal complaint letter

Document 3 — Free Legal Aid Request Letter:
- Professional format
- Formal request to DLEC or NGO
- Case summary included
- Placeholders for user personal details

Every document MUST end with:
DISCLAIMER: Generated by INSAAF OS for informational purposes only. Not legal advice. Consult a licensed lawyer before taking action.

CRITICAL RULE: The language for the PDF content MUST BE ENGLISH OR ROMAN URDU ONLY. DO NOT USE URDU SCRIPT.
Return ONLY valid JSON. Do not include markdown formatting.
"""

def _call_gemini(combined_context: dict):
    client = genai.Client(vertexai=True, project="talash-496612", location="us-central1")
    prompt = f"Context:\n{json.dumps(combined_context)}"
    response = client.models.generate_content(
        model='gemini-1.5-flash',
        contents=prompt,
        config=genai.types.GenerateContentConfig(
            system_instruction=system_prompt,
            response_mime_type="application/json",
            response_schema=PDFContentOutput,
        ),
    )
    return response.text

def _create_pdf(filename: str, title: str, content: str):
    os.makedirs("outputs", exist_ok=True)
    filepath = os.path.join("outputs", filename)
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    story.append(Paragraph(title, styles['Title']))
    story.append(Spacer(1, 12))
    
    # Split content by newlines and add to story
    for line in content.split('\n'):
        if line.strip():
            story.append(Paragraph(line.strip(), styles['Normal']))
            story.append(Spacer(1, 6))
            
    doc.build(story)
    return filepath

def run_pdf_formatter(combined_context: dict) -> dict:
    try:
        result_str = run_agent_with_retry(_call_gemini, combined_context)
        res = json.loads(result_str)
        
        timestamp = int(time.time())
        doc1_path = _create_pdf(f"INSAAF_CaseSummary_{timestamp}.pdf", "Case Summary Report", res.get("document_1_summary", "Missing Content"))
        doc2_path = _create_pdf(f"INSAAF_LegalDraft_{timestamp}.pdf", "Legal Draft", res.get("document_2_draft", "Missing Content"))
        doc3_path = _create_pdf(f"INSAAF_LegalAidLetter_{timestamp}.pdf", "Free Legal Aid Request Letter", res.get("document_3_aid", "Missing Content"))
        
        return {
            "status": "success",
            "pdf_files": [doc1_path, doc2_path, doc3_path]
        }
    except Exception as e:
        logger.error(f"Agent 8 failed: {e}")
        return {
            "agent": "PDFFormatter",
            "status": "failed",
            "fallback_used": True,
            "partial_output": {},
            "reason": str(e),
            "instruction_to_next_agent": "pipeline finished",
            "pdf_files": []
        }
